version: '3.8'
services:
  db:
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - d1zero

networks:
  d1zero:

volumes:
  pgdata: